
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN DIVIDE ELSE EQ FLOAT GT ID IF INT LBRACE LPAREN LT MINUS NUMBER PLUS RBRACE RPAREN SEMICOLON TIMES WHILEprogram : stmt_liststmt_list : stmt_list stmt\n| stmtstmt : decl_stmt\n| assign_stmt\n| if_stmt\n| while_stmtdecl_stmt : type ID SEMICOLONtype : INT\n| FLOATassign_stmt : ID ASSIGN expr SEMICOLONif_stmt : IF LPAREN condition RPAREN LBRACE stmt_list RBRACE\n| IF LPAREN condition RPAREN LBRACE stmt_list RBRACE ELSE LBRACE stmt_list RBRACEwhile_stmt : WHILE LPAREN condition RPAREN LBRACE stmt_list RBRACEcondition : expr EQ expr\n| expr LT expr\n| expr GT exprexpr : expr PLUS expr\n| expr MINUS expr\n| expr TIMES expr\n| expr DIVIDE expr\n| LPAREN expr RPAREN\n| NUMBER\n| ID'
    
_lr_action_items = {'ID':([0,2,3,4,5,6,7,8,12,13,14,16,17,18,19,22,27,28,29,30,31,34,35,36,43,47,48,49,50,51,53,54,55,],[9,9,-3,-4,-5,-6,-7,15,-9,-10,-2,20,20,20,-8,20,-11,20,20,20,20,20,20,20,9,9,9,9,-12,-14,9,9,-13,]),'IF':([0,2,3,4,5,6,7,14,19,27,43,47,48,49,50,51,53,54,55,],[10,10,-3,-4,-5,-6,-7,-2,-8,-11,10,10,10,10,-12,-14,10,10,-13,]),'WHILE':([0,2,3,4,5,6,7,14,19,27,43,47,48,49,50,51,53,54,55,],[11,11,-3,-4,-5,-6,-7,-2,-8,-11,11,11,11,11,-12,-14,11,11,-13,]),'INT':([0,2,3,4,5,6,7,14,19,27,43,47,48,49,50,51,53,54,55,],[12,12,-3,-4,-5,-6,-7,-2,-8,-11,12,12,12,12,-12,-14,12,12,-13,]),'FLOAT':([0,2,3,4,5,6,7,14,19,27,43,47,48,49,50,51,53,54,55,],[13,13,-3,-4,-5,-6,-7,-2,-8,-11,13,13,13,13,-12,-14,13,13,-13,]),'$end':([1,2,3,4,5,6,7,14,19,27,50,51,55,],[0,-1,-3,-4,-5,-6,-7,-2,-8,-11,-12,-14,-13,]),'RBRACE':([3,4,5,6,7,14,19,27,48,49,50,51,54,55,],[-3,-4,-5,-6,-7,-2,-8,-11,50,51,-12,-14,55,-13,]),'ASSIGN':([9,],[16,]),'LPAREN':([10,11,16,17,18,22,28,29,30,31,34,35,36,],[17,18,22,22,22,22,22,22,22,22,22,22,22,]),'SEMICOLON':([15,20,21,23,38,39,40,41,42,],[19,-24,27,-23,-18,-19,-20,-21,-22,]),'NUMBER':([16,17,18,22,28,29,30,31,34,35,36,],[23,23,23,23,23,23,23,23,23,23,23,]),'PLUS':([20,21,23,25,32,38,39,40,41,42,44,45,46,],[-24,28,-23,28,28,28,28,28,28,-22,28,28,28,]),'MINUS':([20,21,23,25,32,38,39,40,41,42,44,45,46,],[-24,29,-23,29,29,29,29,29,29,-22,29,29,29,]),'TIMES':([20,21,23,25,32,38,39,40,41,42,44,45,46,],[-24,30,-23,30,30,30,30,30,30,-22,30,30,30,]),'DIVIDE':([20,21,23,25,32,38,39,40,41,42,44,45,46,],[-24,31,-23,31,31,31,31,31,31,-22,31,31,31,]),'EQ':([20,23,25,38,39,40,41,42,],[-24,-23,34,-18,-19,-20,-21,-22,]),'LT':([20,23,25,38,39,40,41,42,],[-24,-23,35,-18,-19,-20,-21,-22,]),'GT':([20,23,25,38,39,40,41,42,],[-24,-23,36,-18,-19,-20,-21,-22,]),'RPAREN':([20,23,24,26,32,38,39,40,41,42,44,45,46,],[-24,-23,33,37,42,-18,-19,-20,-21,-22,-15,-16,-17,]),'LBRACE':([33,37,52,],[43,47,53,]),'ELSE':([50,],[52,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'stmt_list':([0,43,47,53,],[2,48,49,54,]),'stmt':([0,2,43,47,48,49,53,54,],[3,14,3,3,14,14,3,14,]),'decl_stmt':([0,2,43,47,48,49,53,54,],[4,4,4,4,4,4,4,4,]),'assign_stmt':([0,2,43,47,48,49,53,54,],[5,5,5,5,5,5,5,5,]),'if_stmt':([0,2,43,47,48,49,53,54,],[6,6,6,6,6,6,6,6,]),'while_stmt':([0,2,43,47,48,49,53,54,],[7,7,7,7,7,7,7,7,]),'type':([0,2,43,47,48,49,53,54,],[8,8,8,8,8,8,8,8,]),'expr':([16,17,18,22,28,29,30,31,34,35,36,],[21,25,25,32,38,39,40,41,44,45,46,]),'condition':([17,18,],[24,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> stmt_list','program',1,'p_program','min_comp.py',132),
  ('stmt_list -> stmt_list stmt','stmt_list',2,'p_stmt_list','min_comp.py',136),
  ('stmt_list -> stmt','stmt_list',1,'p_stmt_list','min_comp.py',137),
  ('stmt -> decl_stmt','stmt',1,'p_stmt','min_comp.py',141),
  ('stmt -> assign_stmt','stmt',1,'p_stmt','min_comp.py',142),
  ('stmt -> if_stmt','stmt',1,'p_stmt','min_comp.py',143),
  ('stmt -> while_stmt','stmt',1,'p_stmt','min_comp.py',144),
  ('decl_stmt -> type ID SEMICOLON','decl_stmt',3,'p_decl_stmt','min_comp.py',148),
  ('type -> INT','type',1,'p_type','min_comp.py',154),
  ('type -> FLOAT','type',1,'p_type','min_comp.py',155),
  ('assign_stmt -> ID ASSIGN expr SEMICOLON','assign_stmt',4,'p_assign_stmt','min_comp.py',159),
  ('if_stmt -> IF LPAREN condition RPAREN LBRACE stmt_list RBRACE','if_stmt',7,'p_if_stmt','min_comp.py',166),
  ('if_stmt -> IF LPAREN condition RPAREN LBRACE stmt_list RBRACE ELSE LBRACE stmt_list RBRACE','if_stmt',11,'p_if_stmt','min_comp.py',167),
  ('while_stmt -> WHILE LPAREN condition RPAREN LBRACE stmt_list RBRACE','while_stmt',7,'p_while_stmt','min_comp.py',181),
  ('condition -> expr EQ expr','condition',3,'p_condition','min_comp.py',190),
  ('condition -> expr LT expr','condition',3,'p_condition','min_comp.py',191),
  ('condition -> expr GT expr','condition',3,'p_condition','min_comp.py',192),
  ('expr -> expr PLUS expr','expr',3,'p_expr','min_comp.py',196),
  ('expr -> expr MINUS expr','expr',3,'p_expr','min_comp.py',197),
  ('expr -> expr TIMES expr','expr',3,'p_expr','min_comp.py',198),
  ('expr -> expr DIVIDE expr','expr',3,'p_expr','min_comp.py',199),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr','min_comp.py',200),
  ('expr -> NUMBER','expr',1,'p_expr','min_comp.py',201),
  ('expr -> ID','expr',1,'p_expr','min_comp.py',202),
]
